# Generated by Django 5.2.11 on 2026-02-23 21:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import recruitment.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('cv_file', models.FileField(upload_to=recruitment.models.cv_upload_path)),
                ('cover_letter_file', models.FileField(blank=True, null=True, upload_to=recruitment.models.cover_letter_upload_path)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('nationality', models.CharField(blank=True, help_text='Nationalité', max_length=100)),
                ('university', models.CharField(blank=True, help_text="Établissement d'enseignement", max_length=200)),
                ('degree_level', models.CharField(blank=True, help_text='Diplôme obtenu', max_length=50)),
                ('graduation_year', models.IntegerField(blank=True, help_text="Année d'obtention", null=True)),
                ('experience_years', models.IntegerField(default=0, help_text="Années d'expérience")),
                ('linkedin_url', models.URLField(blank=True, help_text='Lien profil LinkedIn')),
                ('portfolio_url', models.URLField(blank=True, help_text='Lien portfolio/GitHub')),
                ('current_location', models.CharField(blank=True, help_text='Ville actuelle', max_length=100)),
                ('salary_expectation', models.IntegerField(blank=True, help_text='Prétention salariale (Mensuel)', null=True)),
                ('availability_date', models.DateField(blank=True, help_text='Date de disponibilité', null=True)),
                ('ai_score', models.IntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('ai_decision', models.CharField(default='PENDING', max_length=20)),
                ('ai_missing_skills', models.JSONField(blank=True, default=list)),
                ('ai_strengths', models.JSONField(blank=True, default=list)),
                ('ai_weaknesses', models.JSONField(blank=True, default=list)),
                ('ai_recommendations', models.TextField(blank=True, default='')),
                ('ai_candidate_message', models.TextField(blank=True, default='', help_text='Message personnalisé pour le candidat')),
                ('ai_next_steps', models.TextField(blank=True, default='', help_text='Instructions sur les prochaines étapes')),
                ('ai_analysis_date', models.DateTimeField(blank=True, help_text='Date de la dernière analyse IA', null=True)),
            ],
            options={
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('CANDIDATE', 'Candidat'), ('RH', 'Responsable RH'), ('ADMIN', 'Administrateur')], default='CANDIDATE', max_length=20, verbose_name='Rôle')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, related_name='recruitment_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='recruitment_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AIInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('expired', 'Expiré'), ('fraud_terminated', 'Terminé pour fraude')], default='pending', max_length=20)),
                ('current_phase', models.CharField(choices=[('communication', 'Communication'), ('cv_clarification', 'Clarification CV'), ('technical', 'Technique'), ('completed', 'Terminé')], default='communication', max_length=20)),
                ('transcript', models.JSONField(default=list)),
                ('communication_score', models.IntegerField(blank=True, null=True)),
                ('clarification_score', models.IntegerField(blank=True, null=True)),
                ('qcm_score', models.IntegerField(blank=True, null=True)),
                ('coding_score', models.IntegerField(blank=True, null=True)),
                ('ai_interview_score', models.IntegerField(blank=True, null=True)),
                ('ai_interview_feedback', models.TextField(blank=True)),
                ('qcm_questions', models.JSONField(default=list)),
                ('qcm_answers', models.JSONField(default=dict)),
                ('coding_exercise', models.JSONField(default=dict)),
                ('coding_submission', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interview', to='recruitment.application')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.application')),
                ('rh_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_type', models.CharField(choices=[('tab_switch', 'Changement onglet'), ('copy_paste', 'Copier-coller détecté'), ('fullscreen_exit', 'Sortie plein écran'), ('camera_off', 'Caméra désactivée'), ('multiple_faces', 'Plusieurs visages détectés')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(blank=True, max_length=200)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='recruitment.aiinterview')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('weight_cv', models.FloatField(default=0.5, help_text='Poids CV (0-1)')),
                ('weight_motivation', models.FloatField(default=0.15, help_text='Poids lettre motivation (0-1)')),
                ('weight_softskills', models.FloatField(default=0.1, help_text='Poids soft skills (0-1)')),
                ('weight_github', models.FloatField(default=0.25, help_text='Poids GitHub (0-1)')),
                ('offer_deadline', models.DateField(blank=True, null=True)),
                ('agents_needed', models.IntegerField(default=1)),
                ('interview_type', models.CharField(choices=[('RH', 'Entretien RH'), ('AI', 'Entretien IA')], default='AI', max_length=20)),
                ('deadline_processed', models.BooleanField(default=False)),
                ('location', models.CharField(default='Tunisie', max_length=100)),
                ('contract_type', models.CharField(default='CDI', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Offre active')),
                ('requirements', models.TextField(help_text='Compétences techniques séparées par des virgules')),
                ('experience_years', models.PositiveIntegerField(default=0, help_text="Années d'expérience requises")),
                ('education_level', models.CharField(choices=[('BAC', 'Baccalauréat'), ('BAC+2', 'BAC+2 (DUT/BTS)'), ('BAC+3', 'Licence'), ('BAC+5', 'Master / Ingénieur'), ('PHD', 'Doctorat')], default='BAC+5', max_length=20)),
                ('soft_skills', models.TextField(blank=True, help_text="Compétences douces (ex: Travail d'équipe, Communication)")),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='job_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.joboffer'),
        ),
        migrations.CreateModel(
            name='RHAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], help_text='Jour de la semaine (récurrence)', null=True)),
                ('specific_date', models.DateField(blank=True, help_text='Date spécifique (exception)', null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rh_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['specific_date', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='RHSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disable_weekends', models.BooleanField(default=True)),
                ('enable_lunch_break', models.BooleanField(default=True)),
                ('default_interview_duration', models.IntegerField(default=60)),
                ('lunch_break_start', models.TimeField(default='12:00')),
                ('lunch_break_end', models.TimeField(default='13:00')),
                ('rh_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rh_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RHAvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rh_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('rh_user', 'date')},
            },
        ),
    ]
