# Generated by Django 5.2.11 on 2026-02-24 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hired_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_stage',
            field=models.CharField(blank=True, choices=[('cv_screening', 'Screening CV'), ('ai_analysis', 'Analyse IA'), ('interview', 'Entretien'), ('final', 'Décision finale')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('direct', 'Candidature directe'), ('referral', 'Recommandation'), ('other', 'Autre')], default='direct', max_length=50),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='contract_duration',
            field=models.IntegerField(blank=True, help_text='Durée en mois (null si CDI)', null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='department',
            field=models.CharField(choices=[('tech', 'Technologie'), ('rh', 'Ressources Humaines'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('commercial', 'Commercial'), ('operations', 'Opérations'), ('other', 'Autre')], default='tech', max_length=50),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='filled_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='required_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RHMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='Format : 2024-01', max_length=7, unique=True)),
                ('total_offers', models.IntegerField(default=0)),
                ('total_applications', models.IntegerField(default=0)),
                ('total_hired', models.IntegerField(default=0)),
                ('total_rejected', models.IntegerField(default=0)),
                ('total_interviews_completed', models.IntegerField(default=0)),
                ('avg_time_to_hire', models.FloatField(default=0, help_text='Temps moyen en jours')),
                ('avg_ai_score', models.FloatField(default=0)),
                ('avg_interview_score', models.FloatField(default=0)),
                ('conversion_rate', models.FloatField(default=0, help_text='Taux candidature→embauche en %')),
                ('interview_completion_rate', models.FloatField(default=0, help_text='Taux completion entretien IA en %')),
                ('fraud_rate', models.FloatField(default=0, help_text='Taux fraude entretien en %')),
                ('by_department', models.JSONField(default=dict, help_text='Métriques par département')),
                ('by_source', models.JSONField(default=dict, help_text='Candidatures par source')),
                ('by_contract_type', models.JSONField(default=dict, help_text='Candidatures par type contrat')),
                ('rejection_by_stage', models.JSONField(default=dict, help_text='Rejets par étape du process')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Métriques RH',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='CVMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField(help_text='Score de matching 0-100')),
                ('matching_skills', models.JSONField(default=list, help_text='Compétences communes')),
                ('missing_skills', models.JSONField(default=list, help_text='Compétences manquantes')),
                ('match_summary', models.TextField(blank=True, help_text='Résumé IA du matching')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_matches', to='recruitment.application')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_matches', to='recruitment.joboffer')),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('job_offer', 'application')},
            },
        ),
    ]
