# Generated by Django 5.2.11 on 2026-02-26 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_application_hired_at_application_rejection_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RHNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('urgent', 'Urgent')], default='info', max_length=10)),
                ('notify_at', models.DateTimeField(blank=True, null=True)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='recruitment.application')),
                ('linked_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='recruitment.joboffer')),
                ('rh_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rh_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rh_notes',
                'ordering': ['date', 'notify_at'],
            },
        ),
    ]
