# Generated by Django 5.2.11 on 2026-02-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_alter_application_options_alter_joboffer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rhsettings',
            name='lunch_break_end',
            field=models.TimeField(default='13:00'),
        ),
        migrations.AddField(
            model_name='rhsettings',
            name='lunch_break_start',
            field=models.TimeField(default='12:00'),
        ),
    ]
