# Generated by Django 5.2.11 on 2026-03-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_auto_20260322_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='portfolio_url',
        ),
        migrations.AddField(
            model_name='application',
            name='github_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='github_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='github_username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='github_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='linkedin_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='linkedin_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='linkedin_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
