# Generated by Django 5.2.11 on 2026-02-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_rhsettings_lunch_break_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rhavailability',
            options={},
        ),
        migrations.AddField(
            model_name='rhavailability',
            name='specific_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rhavailability',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], null=True),
        ),
    ]
