# Generated by Django 5.2.11 on 2026-02-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_alter_rhavailability_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rhavailability',
            options={'ordering': ['specific_date', 'day_of_week', 'start_time']},
        ),
        migrations.AlterField(
            model_name='rhavailability',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], help_text='Jour de la semaine (récurrence)', null=True),
        ),
        migrations.AlterField(
            model_name='rhavailability',
            name='specific_date',
            field=models.DateField(blank=True, help_text='Date spécifique (exception)', null=True),
        ),
    ]
