# Generated by Django 5.2.11 on 2026-04-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_alter_application_github_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterview',
            name='video_recording',
            field=models.FileField(blank=True, null=True, upload_to='interview_videos/%Y/%m/'),
        ),
    ]
