# Generated by Django 5.2.11 on 2026-02-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_rhavailabilityexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='education_level',
            field=models.CharField(choices=[('BAC', 'Baccalauréat'), ('BAC+2', 'BAC+2 (DUT/BTS)'), ('BAC+3', 'Licence'), ('BAC+5', 'Master / Ingénieur'), ('PHD', 'Doctorat')], default='BAC+5', max_length=20),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text="Années d'expérience requises"),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='soft_skills',
            field=models.TextField(blank=True, help_text="Compétences douces (ex: Travail d'équipe, Communication)"),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='requirements',
            field=models.TextField(help_text='Compétences techniques séparées par des virgules'),
        ),
    ]
