# Generated by Django 5.2.11 on 2026-04-19 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_aiinterview_video_recording'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('meeting_link', models.URLField(blank=True, help_text='Lien visioconférence ou adresse physique', null=True)),
                ('interviewer_name', models.CharField(help_text="Nom de l'interviewer", max_length=200)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyée'), ('accepted', 'Acceptée'), ('declined', 'Refusée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_response', models.TextField(blank=True, help_text='Réponse du candidat si accepté/refusé')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_invitations', to='recruitment.application')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
