# Generated by Django 5.2.11 on 2026-02-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_joboffer_education_level_joboffer_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='availability_date',
            field=models.DateField(blank=True, help_text='Date de disponibilité', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='current_location',
            field=models.CharField(blank=True, help_text='Ville actuelle', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='degree_level',
            field=models.CharField(blank=True, help_text='Diplôme obtenu', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='experience_years',
            field=models.IntegerField(default=0, help_text="Années d'expérience"),
        ),
        migrations.AddField(
            model_name='application',
            name='graduation_year',
            field=models.IntegerField(blank=True, help_text="Année d'obtention", null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Lien profil LinkedIn'),
        ),
        migrations.AddField(
            model_name='application',
            name='nationality',
            field=models.CharField(blank=True, help_text='Nationalité', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Lien portfolio/GitHub'),
        ),
        migrations.AddField(
            model_name='application',
            name='salary_expectation',
            field=models.IntegerField(blank=True, help_text='Prétention salariale (Mensuel)', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='university',
            field=models.CharField(blank=True, help_text="Établissement d'enseignement", max_length=200),
        ),
    ]
