# Generated by Django 5.2.11 on 2026-02-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_application_availability_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='contract_type',
            field=models.CharField(default='CDI', max_length=50),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='location',
            field=models.CharField(default='Tunisie', max_length=100),
        ),
    ]
