# Generated by Django 5.2.11 on 2026-02-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_joboffer_contract_type_joboffer_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_decision',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_missing_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_recommendations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_strengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_weaknesses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
