# Generated by Django 5.2.11 on 2026-04-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_alter_user_groups_alter_user_user_permissions'),
        ('recruitment', '0013_fix_user_m2m'),
    ]

    operations = [
    ]
