# Generated by Django 5.2.11 on 2026-04-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0014_merge_20260421_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CANDIDATE', 'Candidat'), ('RH', 'Responsable RH'), ('ADMIN', 'Administrateur')], default='CANDIDATE', max_length=20),
        ),
    ]
