# Generated by Django 5.2.11 on 2026-04-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0015_alter_user_options_alter_user_email_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
