# Generated by Django 5.2.11 on 2026-04-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0017_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_certifications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_projects',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
