# Generated by Django 5.2.11 on 2026-04-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0018_application_ai_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='extra_profile_details',
            field=models.JSONField(blank=True, default=dict, help_text="Stocke les certifications et liens sous forme { 'certif': '...', 'link': '...' }"),
        ),
    ]
