# Generated by Django 5.2.11 on 2026-04-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0019_application_extra_profile_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
