# Generated by Django 5.2.11 on 2026-04-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0020_application_certificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_detailed_justification',
            field=models.JSONField(blank=True, default=dict, help_text='Justification détaillée par composant'),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_notes',
            field=models.TextField(blank=True, help_text="Notes additionnelles de l'analyse IA", null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_score_rationale',
            field=models.TextField(blank=True, help_text='Explication détaillée du score IA', null=True),
        ),
    ]
