# Generated by Django 5.2.11 on 2026-04-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0021_application_ai_detailed_justification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cin_file',
            field=models.FileField(blank=True, null=True, upload_to='employees/cin/'),
        ),
        migrations.AddField(
            model_name='application',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='employees/contracts/'),
        ),
        migrations.AddField(
            model_name='application',
            name='criminal_record_file',
            field=models.FileField(blank=True, null=True, upload_to='employees/criminal/'),
        ),
        migrations.AddField(
            model_name='application',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='diplomas_file',
            field=models.FileField(blank=True, null=True, upload_to='employees/diplomas/'),
        ),
        migrations.AddField(
            model_name='application',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='medical_file',
            field=models.FileField(blank=True, null=True, upload_to='employees/medical/'),
        ),
        migrations.AddField(
            model_name='application',
            name='photo_file',
            field=models.FileField(blank=True, null=True, upload_to='employees/photos/'),
        ),
        migrations.AddField(
            model_name='application',
            name='position_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rib_file',
            field=models.FileField(blank=True, null=True, upload_to='employees/rib/'),
        ),
        migrations.AddField(
            model_name='application',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
