# Generated by Django 5.2.11 on 2026-04-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0022_application_cin_file_application_contract_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Candidature reçue'), ('qualified', 'Qualifié après IA'), ('invited', 'Invité entretien final'), ('rejected', 'Rejeté'), ('hired', 'Recruté')], default='pending', max_length=20),
        ),
    ]
