# Generated by Django 5.2.11 on 2026-04-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0023_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterview',
            name='override_recommendation',
            field=models.CharField(blank=True, help_text='Override RH de la recommandation IA : VALIDATED | TO_REVIEW | REJECTED', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aiinterview',
            name='phase_started_at',
            field=models.DateTimeField(blank=True, help_text='Horodatage de début de la phase courante (contrôle chrono)', null=True),
        ),
        migrations.AddField(
            model_name='aiinterview',
            name='qcm_started_at',
            field=models.DateTimeField(blank=True, help_text='Horodatage de début du QCM (contrôle chrono)', null=True),
        ),
        migrations.AddField(
            model_name='aiinterview',
            name='rh_annotated_at',
            field=models.DateTimeField(blank=True, help_text='Date de la dernière annotation RH', null=True),
        ),
        migrations.AddField(
            model_name='aiinterview',
            name='rh_annotation',
            field=models.TextField(blank=True, help_text='Note libre du RH après visionnage de la vidéo', null=True),
        ),
        migrations.AddField(
            model_name='aiinterview',
            name='rh_rating',
            field=models.IntegerField(blank=True, help_text='Note manuelle RH 1-5', null=True),
        ),
        migrations.AddField(
            model_name='aiinterview',
            name='scenario_questions',
            field=models.JSONField(blank=True, default=list, help_text='Scénarios pré-générés avec evaluation_criteria'),
        ),
        migrations.AddField(
            model_name='aiinterview',
            name='scenario_score',
            field=models.IntegerField(blank=True, help_text='Score phase mise en situation (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='aiinterview',
            name='current_phase',
            field=models.CharField(choices=[('communication', 'Communication'), ('cv_clarification', 'Clarification CV'), ('scenario', 'Mise en situation'), ('technical', 'Technique'), ('completed', 'Terminé')], default='communication', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewwarning',
            name='warning_type',
            field=models.CharField(choices=[('tab_switch', 'Changement onglet'), ('copy_paste', 'Copier-coller détecté'), ('fullscreen_exit', 'Sortie plein écran'), ('camera_off', 'Caméra désactivée'), ('multiple_faces', 'Plusieurs visages détectés'), ('face_not_visible', 'Visage non visible'), ('phone_detected', 'Téléphone détecté'), ('window_blur', 'Fenêtre en arrière-plan'), ('screen_share_stopped', 'Partage écran interrompu'), ('time_exceeded', 'Temps dépassé')], max_length=50),
        ),
    ]
