# Generated by Django 5.2.11 on 2026-04-27 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0024_aiinterview_override_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='current_position',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='github_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='application',
            name='linkedin_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du certificat', max_length=200)),
                ('issuing_organization', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='certifications/')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('credential_url', models.URLField(blank=True)),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='recruitment.application')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='Bayt, Indeed, Portfolio...', max_length=50)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_links', to='recruitment.application')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommender_name', models.CharField(max_length=200)),
                ('recommender_position', models.CharField(blank=True, max_length=200)),
                ('recommender_company', models.CharField(blank=True, max_length=200)),
                ('recommender_email', models.EmailField(blank=True, max_length=254)),
                ('recommender_phone', models.CharField(blank=True, max_length=50)),
                ('file', models.FileField(upload_to='recommendations/')),
                ('relationship', models.CharField(choices=[('manager', 'Ancien Manager'), ('colleague', 'Collègue'), ('professor', 'Professeur'), ('client', 'Client'), ('other', 'Autre')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_letters', to='recruitment.application')),
            ],
        ),
    ]
