# Generated by Django 5.2.11 on 2026-04-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0025_application_current_position_application_github_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='github_data',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
