# Generated by Django 5.2.11 on 2026-04-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0026_alter_application_github_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='github_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
