# Generated by Django 5.2.11 on 2026-04-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0028_alter_application_github_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_breakdown',
            field=models.JSONField(blank=True, help_text='Détail pondéré du score IA', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_coherence_flags',
            field=models.JSONField(blank=True, default=list, help_text='Alertes de cohérence détectées'),
        ),
    ]
