# Generated by Django 5.2.11 on 2026-04-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0029_application_ai_breakdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterview',
            name='technical_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinterview',
            name='warnings_count',
            field=models.IntegerField(default=0),
        ),
    ]
