# Generated by Django 5.2.11 on 2026-05-05 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0031_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='application_data',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='cover_letter_path',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='cv_file_path',
        ),
        migrations.AddField(
            model_name='application',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to='recruitment.application'),
        ),
    ]
