# Generated by Django 5.2.11 on 2026-05-20 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0032_remove_emailverification_application_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom entreprise')),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/')),
                ('email_domain', models.CharField(blank=True, help_text='ex: acme.com', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('max_rh_users', models.IntegerField(default=5)),
                ('max_active_offers', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CANDIDATE', 'Candidat'), ('RH', 'Responsable RH'), ('ADMIN_RH', 'Admin RH entreprise'), ('SUPERADMIN', 'Super Admin plateforme')], default='CANDIDATE', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='recruitment.company'),
        ),
    ]
