# Generated by Django 5.2.11 on 2026-05-20 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0033_company_alter_user_role_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='recruitment.company'),
        ),
    ]
