# Generated by Django 5.2.11 on 2026-05-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0035_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RH', 'Responsable RH'), ('ADMIN', 'Admin RH entreprise'), ('SUPERADMIN', 'Super Admin plateforme')], default='CANDIDATE', max_length=20),
        ),
    ]
