# Generated by Django 5.2.11 on 2026-05-21 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0036_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
