# Generated by Django 5.2.11 on 2026-05-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0037_activitylog_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at'], 'verbose_name': "Log d'Activité", 'verbose_name_plural': "Logs d'Activité"},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='timestamp',
        ),
    ]
