# Generated by Django 5.2.11 on 2026-05-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0038_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='salary_currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('TND', 'Tunisian Dinar')], default='EUR', max_length=3, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire maximum'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire minimum'),
        ),
    ]
