# Generated by Django 5.2.11 on 2026-05-28 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0039_joboffer_salary_currency_joboffer_salary_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applied_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
