# Generated by Django 5.2.11 on 2026-06-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0040_alter_application_applied_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_github_metrics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
