# Generated by Django 5.2.11 on 2026-06-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0041_application_ai_github_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='degree_level',
            field=models.CharField(blank=True, help_text='Diplôme obtenu', max_length=200),
        ),
    ]
