# Generated by Django 5.2.11 on 2026-06-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0042_alter_application_degree_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiinterview',
            name='coding_exercise',
        ),
        migrations.RemoveField(
            model_name='aiinterview',
            name='coding_score',
        ),
        migrations.RemoveField(
            model_name='aiinterview',
            name='coding_submission',
        ),
        migrations.AddField(
            model_name='aiinterview',
            name='technical_questions',
            field=models.JSONField(blank=True, default=list, help_text='Questions techniques orales pré-générées avec angles'),
        ),
    ]
