# Generated by Django 5.2.11 on 2026-06-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0043_remove_aiinterview_coding_exercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='cached_qcm_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='cached_qcm_questions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
