# Generated by Django 5.2.11 on 2026-06-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0044_joboffer_cached_qcm_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterview',
            name='qcm_from_cache',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiinterview',
            name='qcm_skipped',
            field=models.BooleanField(default=False),
        ),
    ]
