# Generated by Django 5.2.11 on 2026-06-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0045_aiinterview_qcm_from_cache_aiinterview_qcm_skipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiinterview',
            name='video_recording',
        ),
        migrations.AddField(
            model_name='aiinterview',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
