# Generated by Django 5.2.11 on 2026-06-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0046_remove_aiinterview_video_recording_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='github_code_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='github_code_samples',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
