# Generated by Django 5.2.11 on 2026-06-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0048_alter_application_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_cert_verifications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
